### ISSUE TITLE
route not found when sending get request parameters

### ISSUE THREAD

**Issue by szabgab** [ufobat/Bailador#17]
I have the most simple  application:

```
get '/' => sub {
    "hello world"
}
```

If I access `/` it works but if I request `/?anything`  it does not find the route any more.

**Comment by tadzik** [comment]
So, does the commit in your fork fix it, any reason why it shouldn't be in the main repo?

**Comment by Emeric54** [comment]
Is seems it has been fixed. I think we can close this issue ! 🔚

**Comment by ufobat** [comment]
thanks :)
