### ISSUE TITLE
Rapid requests kill the server

### ISSUE THREAD

**Issue by zoffixznet** [ufobat/Bailador#42]
It seems the server dies if too many requests are sent rapidly.

#### Steps to reproduce

1) Get code
```bash
panda install MIME::Types;
cd $(mktemp -d);
git clone https://github.com/zoffixznet/p6high.xtatik.org.git .
git checkout 1f79b6fcf37c71f9b367b33e1a1f19583504ca3b;
perl6 site.pl6;
```
2) Go to [http://localhost:3000/public/scss/bootstrap.min.css](http://localhost:3000/public/scss/bootstrap.min.css)
3) Press F5 (refresh) key rapidly

#### Expected results
Server keeps serving the file

#### Current results
The server crashes. No error messages or anything, it just seems to simply exit.

**Comment by tadzik** [comment]
This should actually be reported to https://github.com/supernovus/perl6-http-easy I think, which bailador uses as its development server. Or is it actually the case that it works for HTTP::Easy but some of the bailador stuff breaks it? Last time I checked HTTP::Easy fell to port scanning too.

**Comment by zoffixznet** [comment]
Can't reproduce anymore. Closing.
