### ISSUE TITLE
A website for Bailador ?

### ISSUE THREAD

**Issue by Emeric54** [ufobat/Bailador#45]
Hello World,

I think it would be a great idea to create a website for Bailador. No need some complicated thing, just a simple site. In my opinion, [perldancer.org](http://perldancer.org/) is a good example.

It would also be a good opportunity to write a documentation.

What's your opinion ?

**Comment by tadzik** [comment]
Sounds like a good idea. Any volunteers? :)

**Comment by Emeric54** [comment]
I can help !
Le 22 févr. 2016 17:50, "Tadeusz Sośnierz" <notifications@github.com> a
écrit :

**Comment by tadzik** [comment]
That'd be awesome :) Would you like to lead that project? I'm not the best at websites :)

**Comment by Emeric54** [comment]
I'm very busy at the moment, but I'll try to do something. I'll show my progress here. So, any help is welcome ! ;-)

**Comment by Emeric54** [comment]
It would be great to have a logo for Bailador (even something simple). Unfortunately, I'm not very good at it. Can anyone do it ? That'd would be super !
