### ISSUE TITLE
Customizing Error 500

### ISSUE THREAD

**Issue by Emeric54** [ufobat/Bailador#47]
I've a very simple application : 
```perl6
use v6;

use Bailador;

get '/' => sub {
  die "Argh !";
}

baile;
```
This application will return me a `Internal Server Error`. It would be interesting to customize this page if necessary.

For example, if a `500.x` file exists in the templates directory, it will be returned by default.

What's your opinion ?

**Comment by tadzik** [comment]
Would be nice to have indeed, and shouldn't be very hard to do either :)

**Comment by Emeric54** [comment]
I think there are 2 ways to do it : 
- As I said, if a `500.xx` file exists in the templates directory, it will be returned by default ;

- We also can do something like Sinatra : 
```ruby
error do
    'Text of error page'
end
```

**Comment by tadzik** [comment]
I think it makes more sense to follow Dancer(2)'s design choices more 
than Sinatras. IIRC they're using the 500.xx files, right?

**Comment by Emeric54** [comment]
Yes, you're right. Let's do it ! :)

**Comment by ufobat** [comment]
Documentation needed!

**Comment by Altai-man** [comment]
Someone more native should document it, since my Enrgish is less than awesome.

**Comment by ufobat** [comment]
added documentation and a test case
