### ISSUE TITLE
Routing by junctions

### ISSUE THREAD

**Issue by Altai-man** [ufobat/Bailador#72]
In the examples, in file `app.pl6` we have this code:

```perl6
# junctions work too
get any('/h', '/help', '/halp') => sub {
    "junctions are cool"
}
```

But this code doesn't work. It'll be good to comment it until this feature will be implemented.

Do you have any plans on the implementation?

**Comment by zoffixznet** [comment]
As I mentioned on IRC, I think adding `Junction` support is over-engineering. It adds extra maintenance and extra documentation for users to use for little benefit. In my 8-9 carrier as a developer I don't think I needed to have multiple URLs perform same function and if such situation ever comes up, using regexes or named subs is a very simple available alternative.

:-1: on adding Junctions. I've submitted PR #77 to remove them from the aforementioned example code.
