### ISSUE TITLE
Issue Merging Global Symbols (Store)

### ISSUE THREAD

**Issue by tsalada** [ufobat/Bailador#79]
I'm using Rakudo Star 2016.04 on Windows. Bailador won't start. Error output is as follows: 

Entering the development dance floor: http://0.0.0.0:3000
[2016-05-06T18:34:59Z] Started HTTP server.
[2016-05-06T18:35:32Z] GET / HTTP/1.1
P6M Merging GLOBAL symbols failed: duplicate definition of symbol Store
  in any merge_globals at gen/moar/m-ModuleLoader.nqp line 177
  in any merge_globals at gen/moar/m-ModuleLoader.nqp line 163
  in any merge_globals at gen/moar/m-ModuleLoader.nqp line 163
  in submethod BUILD at sources\1C8F9756FC6B9A2436147DB7CA0ED3E2A868F4B4 (Bailador::Sessions) line 18
  in method sessions at sources\06F75D046213CAD92B84F66E5F161C084878D0C3 (Bailador::App) line 49
  in method session at sources\06F75D046213CAD92B84F66E5F161C084878D0C3 (Bailador::App) line 54
  in sub session at C:\rakudo\share\perl6\site\sources\D57520A5A045A33D405E36DAA759641E90C1FD99 (Bailador) line 66
  in sub  at begin_life.pl6 line 15
  in block  at C:\rakudo\share\perl6\site\sources\A80D3EE41ED647143B6A367AAE142A5967A850D7 line 17
  in method recurse-on-routes at C:\rakudo\share\perl6\site\sources\A80D3EE41ED647143B6A367AAE142A5967A850D7 line 13
  in method dispatch at sources\06F75D046213CAD92B84F66E5F161C084878D0C3 (Bailador::App) line 85
  in block  at sources\06F75D046213CAD92B84F66E5F161C084878D0C3 (Bailador::App) line 75

P6M Merging GLOBAL symbols failed: duplicate definition of symbol Store
  in sub encode-psgi-response at sources\4495C7B7918EE565D66335BB81FAC9AD441D4477 (PSGI) line 94
  in method handler at sources\7A1CB8E5EE1C15B75635DFF3AB1EF14A59C13BED (HTTP::Easy::PSGI) line 45
  in method run at sources\1E501B4ADD181EB20112AA83E1326E07497BC6F5 (HTTP::Easy) line 184
  in sub baile at C:\rakudo\share\perl6\site\sources\D57520A5A045A33D405E36DAA759641E90C1FD99 (Bailador) line 91
  in block <unit> at begin_life.pl6 line 36

**Comment by ufobat** [comment]
Could you provide a little example that demonstrates this error?

**Comment by ufobat** [comment]
closed because it seems to be a perl6 internal issue
