### ISSUE TITLE
views/ path should default to '.'

### ISSUE THREAD

**Issue by drforr** [ufobat/Bailador#85]
That way accessing template 'foo.tt' works "out of the box" rather than having to subclass Bailador::App in order to call Bailador::App.new( :location( '.' ) ); I think this is Dancer default, and will help people trying to transition from Dancer to Bailador. It violated the Principle of Least Surprise for me, at the least. I'll submit a patch in a few minutes as well.

**Comment by drforr** [comment]
Incidentally my test script does call Bailador::App.import, which should initialize app.location, but I don't think it's being properly invoked. I've forked and will submit a PR for this momentarily.

**Comment by ufobat** [comment]
PR merged
