### ISSUE TITLE
Internal error: invalid thread ID 145 in GC work pass

### ISSUE THREAD

**Issue by nige123** [ufobat/Bailador#87]
Just wanted to report this bug. The Bailador server regularly crashes with this error:

 Internal error: invalid thread ID 145 in GC work pass

I'm currently on:

This is Rakudo version 2016.09-19-g8be36b1 built on MoarVM version 2016.09
implementing Perl 6.c.

I'm afraid I can't reliably replicate it as it seems to occur randomly.

**Comment by ufobat** [comment]
closed because it seems to be a perl6 internal issue
