### ISSUE TITLE
MoarVM panic: Internal error: zeroed target thread ID in work pass

### ISSUE THREAD

**Issue by nige123** [ufobat/Bailador#93]
I'm intermittently seeing this occur in Bailador:

MoarVM panic: Internal error: zeroed target thread ID in work pass

The result is the server comes to a complete halt - ouch!

Here is the current Perl 6 version I'm using:

This is Rakudo version 2016.12-95-ga6c37a7 built on MoarVM version 2016.12-6-g65acd55
implementing Perl 6.c.

**Comment by ufobat** [comment]
I am afraid I can't help since this is something inside the MoarVM

**Comment by ufobat** [comment]
closed because it seems to be a perl6 internal issue
